// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Role      string       `json:"role"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
