// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Username  string
	Email     string
	Role      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
